#!/bin/bash
. ~/.config/HyprV/hyprv.conf

restart_waybar() {
    #restart the waybar
    pkill waybar
    waybar & 
}

set_current_background() {
  swww img $SET_BG
}

switch_keyboard() {
  hyprctl switchxkblayout $SET_KB next
}

if [[ "$1" == "setbg" ]]; then
    set_current_background
    restart_waybar
elif [[ "$1" == "swkb" ]]; then
    switch_keyboard
fi
